### ISSUE TITLE
DHCP flag setting not transferred to the config.json file.

### ISSUE THREAD

**Issue by MartinMueller2003** [forkineye/ESPSFlashTool#15]
When the user clears the DHCP flag on the UI, the IP addresses are transferred to the config.json file but the Use DHCP flag is always set to "true". I manually set the DHCP flag to false and then the flash tool overwrote the value to "true" indicating that the export operation is setting the DHCP flag to the wrong value.

![image](https://user-images.githubusercontent.com/8608503/206565572-2e7effef-321a-4266-aa52-41e191374337.png)

    "ip": "192.168.10.84",
    "netmask": "255.255.255.0",
    "gateway": "192.168.10.1",
    "dhcp": true,

**Comment by forkineye** [comment]
Did https://github.com/forkineye/ESPSFlashTool/pull/19 fix this as well?

**Comment by MartinMueller2003** [comment]
Yes this is now fixed.
