### ISSUE TITLE
upgrade jSerialComm >= v2.7.0 | Add support for Apple Silicon / AArm64/aarch64

### ISSUE THREAD

**Issue by mores** [forkineye/ESPSFlashTool#16]
4/14/2021 native support for Apple Silicon was added to jSerialComm https://github.com/Fazecast/jSerialComm/pull/343

10/22/2021 jSerialComm released v2.7.0 https://github.com/Fazecast/jSerialComm/releases/tag/v2.7.0

**Comment by forkineye** [comment]
What JRE versions have you tested this with?  I'll test it myself later today and get it merged.
thanks,
-shelby

**Comment by mores** [comment]
% java -version
openjdk version "17.0.1" 2021-10-19 LTS
OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)

**Comment by mores** [comment]
The **UI** was tested on Mac M1 - with java 17.0.1

I did NOT test flashing. ( I don't want to accidentally brick my brand new  ESPixelStick )

**Comment by forkineye** [comment]
Well, this completely fell off my radar until someone brought it up recently. Fixed in 330b55519edfc6a63c2189d1de7774875e59d4e5, sorry about that.
