### ISSUE TITLE
Feature Request: Expose config.ap_fallback

### ISSUE THREAD

**Issue by Indemnity83** [forkineye/ESPSFlashTool#4]
There doesn't seem to be any way while using the flash tool to set the ap_fallback mode to true. Would you be willing to accept a PR that either added a checkbox to the UI for the ap_fallback config option. 

An alternative could be to accept an external config.json but that functionality is likely beyond my ability to implement.

**Comment by MartinMueller2003** [comment]
I just added the ability to retrieve a config file from the running ESP. That means I added a parser to make this functionality work :). I will add general support for controlling this setting via the flashtool.

**Comment by MartinMueller2003** [comment]
FYI: The default value is "true".

**Comment by MartinMueller2003** [comment]
Just created a PR that addresses this and additional issues from the ESPixelStick issues pages.
