### ISSUE TITLE
Can't run in OSX

### ISSUE THREAD

**Issue by philspitlerSF** [forkineye/ESPSFlashTool#5]
The readme says "`Additionally for macOS, you will have to jump through Apple's typical security hoops to allow non-Apple signed software to run."`

But doesn't say how to jump through the hoops.

The UI launches in java ok but once I try and upload I get the error.
`“mklittlefs” cannot be opened because the developer cannot be verified.`

**Comment by forkineye** [comment]
See if this helps - https://support.apple.com/guide/mac-help/open-a-mac-app-from-an-unidentified-developer-mh40616/mac

**Comment by philspitlerSF** [comment]
That usually works but this issue here is that the app I am opening is Java which opens ok... but then Java tries to run mklittlefs which is the issue.. The link above doesn't solve for that.

**Comment by forkineye** [comment]
> That usually works but this issue here is that the app I am opening is Java which opens ok... but then Java tries to run mklittlefs which is the issue.. The link above doesn't solve for that.

You may have to do it twice. Once for the jar, and again for mklittlefs.

**Comment by philspitlerSF** [comment]
That worked... thanks
