### ISSUE TITLE
error: failed to open image file

### ISSUE THREAD

**Issue by philspitlerSF** [forkineye/ESPSFlashTool#6]
The image file seems to be in the correct place and I haven't moved any files.

I am using OSX 12.2.1 and ESPixelStick_Firmware-4.0-beta4

<img width="865" alt="Screen Shot 2022-03-12 at 6 43 15 PM" src="https://user-images.githubusercontent.com/15186070/158042683-a7823710-d9b0-4283-84ef-93bcefaf7926.png">

**Comment by philspitlerSF** [comment]
I rebooted and tried again, this time I get a different error. Do I need to put the ESP into a programming mode?
<img width="1524" alt="Screen Shot 2022-03-13 at 9 27 07 PM" src="https://user-images.githubusercontent.com/15186070/158105359-317316f1-180d-4e89-ad24-c77a999ef1e5.png">

**Comment by MartinMueller2003** [comment]
It depends on the type of platform you have. If the platform has a built in USB serial interface then it most likely has support for the MCU programming sequence. If you device does not have the built in USB interface then you will need to manually put the device into the programming mode.

**Comment by philspitlerSF** [comment]
I'm using a D1mini which is supposed to have USB support and I can't find anything about putting it in programming mode.

**Comment by forkineye** [comment]
> I rebooted and tried again, this time I get a different error. Do I need to put the ESP into a programming mode? <img alt="Screen Shot 2022-03-13 at 9 27 07 PM" width="1524" src="https://user-images.githubusercontent.com/15186070/158105359-317316f1-180d-4e89-ad24-c77a999ef1e5.png">

For some reason, it's not finding the required tools. This is likely due to how it was extracted / path issues.  The upload.py script will append the path directories required based upon where it is launched from.  
The directory structure should look similar to the following:
![image](https://user-images.githubusercontent.com/4047923/158807577-f191b944-008e-44db-90f7-beb42e86d707.png)

**Comment by philspitlerSF** [comment]
Ok... I tried a 2nd laptop and it worked without any problems.... No idea why it failed on my first one but I'm sorted now... 

Thanks
